version: '3.9'

x-base: &base
  platform: linux/amd64
  stop_signal: SIGINT
  restart: always 
  labels:
    app: hackaton
  env_file:
    - env/dev.env

services:
  server:
    <<: *base
    build: .
    command: 'python3 /app/app.py'
    ports:
      - "8001:8001"
    volumes:
      - /Users/timurnikolaev/files:/app/uploads

  front:
    <<: *base
    build: /Users/timurnikolaev/Desktop/project/front
    command: 'nginx -g daemon off'
    ports:
      - "4040:4040"

  database:
    <<: *base
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db1
    volumes:
      - /Users/timurnikolaev/db:/var/lib/postgresql/data

