"""add violationlogusers

Revision ID: bfd654653408
Revises: 5305f995b0a5
Create Date: 2024-06-15 15:28:21.868093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfd654653408'
down_revision: Union[str, None] = '5305f995b0a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indifikator_log_users',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('violation_log_users',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('descritpion', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indifikator_log_users_secondary',
    sa.Column('indifikator_id', sa.Uuid(), nullable=False),
    sa.Column('violation_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['indifikator_id'], ['indifikator_log_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['violation_id'], ['violation_log_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('violation_log_users_secondary',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('violation_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['violation_id'], ['violation_log_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('safety_machinery', sa.Column('file_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'safety_machinery', 'files', ['file_id'], ['id'])
    op.add_column('tools', sa.Column('file_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'tools', 'files', ['file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tools', type_='foreignkey')
    op.drop_column('tools', 'file_id')
    op.drop_constraint(None, 'safety_machinery', type_='foreignkey')
    op.drop_column('safety_machinery', 'file_id')
    op.drop_table('violation_log_users_secondary')
    op.drop_table('indifikator_log_users_secondary')
    op.drop_table('violation_log_users')
    op.drop_table('indifikator_log_users')
    # ### end Alembic commands ###
